const userRouter = require("./routes/user");
const authRouter = require("./routes/auth");
const voucherRouter = require("./routes/voucher");
const invoiceRouter = require("./routes/invoice");
const inventoryRouter = require("./routes/inventory");
const quotationRouter = require("./routes/quotation");
const customerRouter = require("./routes/customer");
const itemRouter = require("./routes/item");
const salesInvoiceRouter = require("./routes/salesInvoice");
const accountRouter = require("./routes/account");
const unitRouter = require("./routes/unit");
const chartRouter = require("./routes/chart");
const salesReturn = require("./routes/salesReturn");
const purchaseOrderRouter = require("./routes/purchase/purchaseOrder");
const purchaseBillRouter = require("./routes/purchase/purchaseBill");
const purchaseReturnRouter = require("./routes/purchase/purchaseReturn");
const companyRouter = require("./routes/company");
const statutoryRouter = require("./routes/statutory");

module.exports = function (app) {
  app.use("/api/v1", userRouter);
  app.use("/api/v1", authRouter);
  app.use("/api/v1", voucherRouter);
  app.use("/api/v1", invoiceRouter);
  app.use("/api/v1", inventoryRouter);
  app.use("/api/v1", quotationRouter);
  app.use("/api/v1", customerRouter);
  app.use("/api/v1", itemRouter);
  app.use("/api/v1", salesInvoiceRouter);
  app.use("/api/v1", accountRouter);
  app.use("/api/v1", unitRouter);
  app.use("/api/v1", chartRouter);
  app.use("/api/v1", salesReturn);
  app.use("/api/v1", purchaseOrderRouter);
  app.use("/api/v1", purchaseBillRouter);
  app.use("/api/v1", purchaseReturnRouter);
  app.use("/api/v1", companyRouter);
  app.use("/api/v1", statutoryRouter);
};
